# Generated by Django 6.1 on 2026-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='boardName',
            field=models.CharField(choices=[('Сделать', 'Сделать'), ('В процессе', 'В процессе'), ('На проверке', 'На проверке'), ('Выполнено', 'Выполнено')], default='Сделать', max_length=12),
        ),
    ]
