# Generated by Django 6.1 on 2026-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_task_boardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='boardName',
            field=models.CharField(choices=[('Сделать', 'Todo'), ('В процессе', 'Inprogress'), ('На проверке', 'Review'), ('Выполнено', 'Done')], default='Сделать', max_length=12),
        ),
    ]
