# Generated by Django 6.1 on 2026-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_task_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(max_length=500, verbose_name='Задача'),
        ),
    ]
