# Generated by Django 6.1 on 2026-08-27 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_task_date_update_remove_task_owner_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 27, 7, 28, 31, 286339, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
