# Generated by Django 6.1 on 2026-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
