# Generated by Django 6.1 on 2026-08-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_alter_task_chief'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
    ]
