# Generated by Django 6.1 on 2026-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_alter_task_chief_alter_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_update',
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
