# Generated by Django 6.1 on 2026-08-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_remove_task_date_update_task_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
    ]
