# Generated by Django 6.1 on 2026-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_remove_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
