# Generated by Django 6.1 on 2026-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_task_comment_task_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
