# Generated by Django 6.1 on 2026-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_task_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
