# Generated by Django 6.1 on 2026-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_alter_task_chief_taskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла'),
        ),
    ]
