# Generated by Django 6.1 on 2026-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_alter_taskattachment_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_api_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение через фронтенд'),
        ),
    ]
